"""user e email nullable

Revision ID: 87a419283aac
Revises: 9dac662f1b30
Create Date: 2026-04-29 23:36:45.791580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '87a419283aac'
down_revision: Union[str, Sequence[str], None] = '9dac662f1b30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Jogador', 'user',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('Jogador', 'email',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
    op.add_column('Jogo', sa.Column('local', sa.String(length=255), nullable=True))
    op.alter_column('Jogo', 'fk_Competicao_id',
               existing_type=mysql.INTEGER(unsigned=True),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Jogo', 'fk_Competicao_id',
               existing_type=mysql.INTEGER(unsigned=True),
               nullable=False)
    op.drop_column('Jogo', 'local')
    op.alter_column('Jogador', 'email',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
    op.alter_column('Jogador', 'user',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
